### ISSUE TITLE
Chat icon on Windows 7 with tooltips

### ISSUE THREAD

**Issue by jerone** [benjamindean/atom-notifier#1]
Tested this working on Windows 7 with tooltips :+1: 

I do have one suggestion to change the chat-like :speech_balloon: icon that appears below the tooltip tip on W7 to the Atom logo. According the docs :memo: from [Notifu](http://www.paralint.com/projects/notifu/) this is possible.

![2015-07-19 15_49_12-](https://cloud.githubusercontent.com/assets/55841/8766183/196cc0f8-2e2e-11e5-8cf1-f601561a9ef7.png)

**Comment by benjamindean** [comment]
@jerone Yep, and this should work, however, 512x512, probably, too big for Win7 tray area. 
I made 16x16 icon for this and a little check for `Windows NT 6.1`.

Can you, please, verify if it works? If it does, probably 32x32 icon would work too. 
Pushed 0.2.3 release few moments ago.

**Comment by jerone** [comment]
No success. Installed latest version (v0.2.3) and still have the same icon as screenshot above.

**Comment by jerone** [comment]
Seems related to the first issue mentioned here: https://github.com/mikaelbr/node-notifier/issues/38

A very small comment [here](https://github.com/mikaelbr/node-notifier#cross-platform-advanced-usage) indicates that icons for balloons aren't supported in the Cross-Platform code:

> `icon: path.join(__dirname, 'coulson.jpg'), // absolute path (not balloons)`

**Comment by jerone** [comment]
So after some investigation it seems that [Notifu only](http://src.paralint.com/notifu/trunk/notifu/Icon.cpp) supports [bitmaps, cursors and icons](https://msdn.microsoft.com/en-us/library/ms648045%28VS.85%29.aspx) because of `(HICON)LoadImage(...);`.

One solution is to use the [`appIcon` property](https://github.com/mikaelbr/node-notifier/blob/9da0d758f02de7430e448e3111304185ab3f9f09/lib/utils.js#L249) to differentiate from the normal `icon` property, and use an bitmap or `.ico` file.

**Comment by benjamindean** [comment]
@jerone So, reverting the changes for now.
I'll investigate behavior of balloon in Electron tomorrow. [Looks like](https://github.com/atom/electron/blob/master/docs/api/tray.md#traydisplayballoonoptions) there is some `NativeImage` implementation for that. If this is what I think it is, I'll make a separate notifier for Windows 7.

**Comment by benjamindean** [comment]
@jerone Interesting. The option [would still](https://github.com/mikaelbr/node-notifier/blob/9da0d758f02de7430e448e3111304185ab3f9f09/lib/utils.js#L83) be called `icon`, as I understood. I guess, we can try to use .ico file there.

Published 0.2.5 patch.

**Comment by benjamindean** [comment]
Just tested. Seems fine with 16x16 .ico. :+1: 
32x32 size and any .bmp failed, btw. 

![win7test](https://cloud.githubusercontent.com/assets/5139993/8783298/9ecb9756-2f23-11e5-8bd1-c675ee579d54.png)

@jerone Thank you for your great support!

**Comment by jerone** [comment]
Just had the time to confirm the fix. Great work :+1:

**Comment by jerone** [comment]
This issue appeared again in latest (v0.4.0) version :(

**Comment by benjamindean** [comment]
@jerone Oops, forgot about proper path for .ico. Should be fixed in 0.4.1.

**Comment by jerone** [comment]
Yeah confirmed working again.
